# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575f134530b184778f85a09892b853332fbdcb0dcdb569ae7df6061c560858e38ee21eee8555d2a2de1a0aa7849994189b4d8d507eaac9de3d9ca39ffcb5e9f2

test:
  secret_key_base: dff313333490ed503e6cb83b8c0f3e3bd8290b58caacb3c95d26460901d07d9b89499bff602a2f339293184177d3da13f0a4024da611e326810c4f056d1713ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
